apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
        - name: {{ .Values.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          securityContext:
            privileged: true
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.name }}-folder-data
              mountPath: /certs
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end}}
      volumes:
        - name: {{ .Values.name }}-folder-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-folder-data-disk
